environment:
  global:
    PROJECT_NAME: watchexec
  matrix:
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: stable

# Install Rust and Cargo
# (Based on from https://github.com/rust-lang/libc/blob/master/appveyor.yml)
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS2_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS2_BITS%\bin
  - rustc -V
  - cargo -V

# ???
build: false

# Equivalent to Travis' `script` phase
test_script:
  - cargo test --verbose

before_deploy:
  # Generate artifacts for release
  - cargo build --release
  - mkdir staging
  - copy target\release\watchexec.exe staging
  - cd staging
  - 7z a ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip *
  - appveyor PushArtifact ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip

deploy:
  description: 'Automatically deployed release'
  artifact: /.*\.zip/
  auth_token:
    secure: GFARzIskXsiKURXYX1Lb091r3SlBDlrGX4d52UWrZtkYUhtX8GAtArzgm74viGoKqy22StoahJ6PpyWmJK9y4gSZGcREd4xyvWcga2nz+IzGvHZqr/A20kf/vabSSvoomdX51swCh5DfeA94jGJBp/gLXUiNk/ughGzqGseUl2qBz0edq4B7Si1vygakOQiE/Fc59U0CKJwJ8tQyVSaJhmRRI99of1IwXQMz1PBJ8gKuz8m1TR76NdYA1Hkaom53EKz3/DZIT93GKhkfDdTH1eisKUUNnzePvBwUCQk+ew+0zVXMQ0EF3Ci41n9nZyY2L0lN+p8z2YgbnSl1Pj9aA4B9rU80fwWuLvJgqzuruzori0WvoHJ+4ZP3V+BcZVlEogujLuLM5k6N05OVq+QteVhsyYz79DbyBf93WIfpYYn2LDW3hyACpLUlc8axK8fHQSB6VGXmJBrJsc5/IidN9Dd7eHJE4poBFSsdeQe5yZbfmIL4agLBiA+nwI0mOOtkYS6XqUTMEADO2L7xqu7/CMjICz2756Ep5l1JJxr4C+FEzUqQhN8PRyGyPV7t8nwHosuoFkSU0tsf2CZaAlxPr5pAnXsqxJMhZTvlXbe2nfPNHYPZnKkcsuSL1tCl8ukeSuf5585tg2/MgNtHtQnXEO+HIE5txpfJ6Znac4WGHug=
  provider: GitHub
  on:
    appveyor_repo_tag: true

branches:
  only:
    - appveyor
    - /\d+\.\d+\.\d+/
  except:
    - master
