[package]
name = "watchexec"
version = "0.11.0"
authors = ["Matt Green <mattgreenrocks@gmail.com>"]

[profile.release]
lto = true

[dependencies]
glob = "0.2.11"
log = "0.3.6"
notify = "2.6.3"

[dependencies.clap]
version = "2.14"
default-features = false
features = ["wrap_help"]

[dependencies.env_logger]
version = "0.3.5"
default-features = false
features = []
